package nuchess.ui.root.view;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import java.util.EventObject;

import javax.swing.AbstractListModel;
import javax.swing.DropMode;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;

import nuchess.player.computer.feature.Check;
import nuchess.player.computer.feature.Feature;
import nuchess.player.computer.feature.Mate;

public class BoardEvaluatorConstructorDialog extends JDialog
{
	private static final long serialVersionUID = 135112890706736156L;
	
	private ContentPanel contentPanel;
	
	public BoardEvaluatorConstructorDialog()
	{
		contentPanel = new ContentPanel();
		add(new WeightDecider());
		setSize(800, 400);
	}
	
	/**
	 *
	 * @author Jacob Cohen
	 */
	public class WeightDecider extends javax.swing.JPanel
	{
		private static final long serialVersionUID = -8332408797014422954L;
		
		private DefaultTableModel tableModel;
		private ArrayList<Feature> features;
		private AbstractListModel<Feature> listModel;

	    /**
	     * Creates new form WeightDecider
	     */
	    public WeightDecider()
	    {
	    	features = new ArrayList<Feature>();
	    	features.add(new Mate());
	    	features.add(new Check());
	    	
            tableModel = new DefaultTableModel(new Object[][] {}, new String[] { "Feature", "Weight" })
	    	{
	    		private static final long serialVersionUID = -8225338543361272365L;
				
	    		public boolean isCellEditable(int row, int column)
	    		{
	    			return column == 0 ? false : super.isCellEditable(row, column);
	    		}
	    	};
	    	
	    	listModel = new AbstractListModel<Feature>()
	    	{	            
				private static final long serialVersionUID = -6199430926115424087L;

				public int getSize()
	            {
	            	return features.size();
	            }
	            
	            public Feature getElementAt(int i)
	            {
	            	return features.get(i);
	            }
	    	};
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents()
	    {
	        weightsListScrollPane = new javax.swing.JScrollPane();
	        weightsList = new javax.swing.JList<>();
	        weightsTableScrollPane = new javax.swing.JScrollPane();
	        weightsTable = new javax.swing.JTable();

	        weightsList.setFocusable(false);
	        weightsList.setDragEnabled(true);
	    	weightsList.setDropMode(DropMode.ON);	    		
	        weightsList.setModel(listModel);
	        weightsList.addListSelectionListener(new ListSelectionListener()
	        {
				@Override
				public void valueChanged(ListSelectionEvent e)
				{
					weightsListValueChanged(e);
				}
	        });
	        weightsListScrollPane.setViewportView(weightsList);

	        weightsTable.setModel(tableModel);
	        weightsTableScrollPane.setViewportView(weightsTable);
	        weightsTable.getTableHeader().setReorderingAllowed(false);
	        weightsTable.setColumnSelectionAllowed(false);
	        weightsTable.setRowSelectionAllowed(true);
	        weightsTable.addKeyListener(new KeyListener()
	        {
				@Override
				public void keyTyped(KeyEvent e)
				{
					
				}

				@Override
				public void keyPressed(KeyEvent e)
				{
					if(e.getKeyCode() == KeyEvent.VK_DELETE)
					{
						features.add((Feature) tableModel.getValueAt(weightsTable.getSelectedRow(), 0));
						tableModel.removeRow(weightsTable.getSelectedRow());
						weightsTable.revalidate();
						weightsList.repaint();
					}
				}

				@Override
				public void keyReleased(KeyEvent e)
				{
					
				}
	        });
	        
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(weightsListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(weightsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(weightsListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
	            .addComponent(weightsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
	        );
	    }// </editor-fold>        
	    
	    private void weightsListValueChanged(ListSelectionEvent e)
	    {
	    	if(0 <= weightsList.getSelectedIndex())
	    	{
		    	tableModel.addRow(new Object[] { weightsList.getSelectedValue(), 0 } );
		    	features.remove(weightsList.getSelectedIndex());
		    	weightsList.clearSelection();
		    	weightsList.repaint();
	    	}
	    }
	    
	    // Variables declaration - do not modify                     
	    private javax.swing.JList<Feature> weightsList;
	    private javax.swing.JScrollPane weightsListScrollPane;
	    private javax.swing.JTable weightsTable;
	    private javax.swing.JScrollPane weightsTableScrollPane;
	    // End of variables declaration                   
	}
	
	/**
	 *
	 * @author Jacob Cohen
	 */
	private class ContentPanel extends javax.swing.JPanel {

		private static final long serialVersionUID = 8761297527215222760L;
		
		/**
	     * Creates new form NewJPanel
	     */
	    public ContentPanel() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        jList1 = new javax.swing.JList<>();
	        jButton1 = new javax.swing.JButton();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jComboBox2 = new javax.swing.JComboBox<>();
	        jLabel3 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        jLabel4 = new javax.swing.JLabel();
	        jComboBox3 = new javax.swing.JComboBox<>();
	        jLabel5 = new javax.swing.JLabel();
	        jTextField2 = new javax.swing.JTextField();
	        jTextField3 = new javax.swing.JTextField();
	        jComboBox4 = new javax.swing.JComboBox<>();

	        jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        jScrollPane1.setViewportView(jTable1);

	        jList1.setModel(new javax.swing.AbstractListModel<String>() {
				String[] strings = { "Pawn Material Difference", "Knight Material Difference" };
	            public int getSize() { return strings.length; }
	            public String getElementAt(int i) { return strings[i]; }
	        });
	        jScrollPane2.setViewportView(jList1);

	        jButton1.setText("Confirm");

	        jLabel1.setText("Selection Algorithm");

	        jLabel2.setText("Recurse Depth");

	        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minimax", "Alphabeta" }));

	        jLabel3.setText("Username");

	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField1ActionPerformed(evt);
	            }
	        });

	        jLabel4.setText("Move Orderer");

	        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pawn Material Difference", "Knight Material Difference" }));

	        jLabel5.setText("Hash Size");

	        jTextField2.setText("0");

	        jTextField3.setText("1024");

	        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "KB", "MB", "GB" }));
	        jComboBox4.setSelectedIndex(2);
	        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jComboBox4ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                            .addComponent(jScrollPane2)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(97, 97, 97)
	                                .addComponent(jLabel4)))
	                        .addGap(4, 4, 4)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jScrollPane1)
	                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                        .addGap(0, 0, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(73, 73, 73)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(jLabel5)
	                            .addComponent(jLabel1))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addGroup(layout.createSequentialGroup()
	                                .addComponent(jTextField3)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(93, 93, 93)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(jLabel3)
	                            .addComponent(jLabel2))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jTextField2)
	                            .addComponent(jTextField1))))
	                .addContainerGap())
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel3)
	                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel2)
	                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel5)
	                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel1)
	                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel4)
	                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jButton1)
	                .addContainerGap())
	        );
	    }// </editor-fold>                        

	    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here:
	    }                                           

	    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
	        // TODO add your handling code here:
	    }                                          


	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JComboBox<String> jComboBox2;
	    private javax.swing.JComboBox<String> jComboBox3;
	    private javax.swing.JComboBox<String> jComboBox4;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JList<String> jList1;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JTable jTable1;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField2;
	    private javax.swing.JTextField jTextField3;
	    // End of variables declaration                   
	}
}
