package nuchess.ui.root.view;

import javax.swing.JDialog;

public class ComputerConstructorDialog extends JDialog
{
	private static final long serialVersionUID = -241011733866209931L;
	
	private ContentPanel contentPanel;

	public ComputerConstructorDialog()
	{
		contentPanel = new ContentPanel();
		add(contentPanel);
		setSize(500, 230);
	}
	
	/**
	 *
	 * @author Jacob Cohen
	 */
	public class ContentPanel extends javax.swing.JPanel {
		
		private static final long serialVersionUID = -5624780098397241968L;
		
		/**
	     * Creates new form NewJPanel
	     */
	    public ContentPanel() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        confirmButton = new javax.swing.JButton();
	        selectionAlgorithmLabel = new javax.swing.JLabel();
	        recurseDepthLabel = new javax.swing.JLabel();
	        selectionAlgorithmComboBox = new javax.swing.JComboBox<>();
	        nicknameLabel = new javax.swing.JLabel();
	        nicknameTextField = new javax.swing.JTextField();
	        hashSizeLabel = new javax.swing.JLabel();
	        recurseDepthTextField = new javax.swing.JTextField();
	        hashSizeTextField = new javax.swing.JTextField();
	        hashSizeUnitComboBox = new javax.swing.JComboBox<>();
	        boardEvaluatorLabel = new javax.swing.JLabel();
	        boardEvaluatorCustomizeButton = new javax.swing.JButton();
	        moveEvaluatorCustomizeButton = new javax.swing.JButton();
	        moveEvaluatorLabel = new javax.swing.JLabel();

	        confirmButton.setText("Confirm");
	        confirmButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                confirmButtonActionPerformed(evt);
	            }
	        });

	        selectionAlgorithmLabel.setText("Selection Algorithm");

	        recurseDepthLabel.setText("Recurse Depth");

	        selectionAlgorithmComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minimax", "Alphabeta" }));
	        selectionAlgorithmComboBox.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                selectionAlgorithmComboBoxActionPerformed(evt);
	            }
	        });

	        nicknameLabel.setText("Nickname");

	        nicknameTextField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                nicknameTextFieldActionPerformed(evt);
	            }
	        });

	        hashSizeLabel.setText("Hash Size");

	        recurseDepthTextField.setText("0");
	        recurseDepthTextField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                recurseDepthTextFieldActionPerformed(evt);
	            }
	        });

	        hashSizeTextField.setText("1024");
	        hashSizeTextField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                hashSizeTextFieldActionPerformed(evt);
	            }
	        });

	        hashSizeUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B", "KB", "MB", "GB" }));
	        hashSizeUnitComboBox.setSelectedIndex(2);
	        hashSizeUnitComboBox.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                hashSizeUnitComboBoxActionPerformed(evt);
	            }
	        });

	        boardEvaluatorLabel.setText("Board Evaluator");

	        boardEvaluatorCustomizeButton.setText("Customize");
	        boardEvaluatorCustomizeButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                boardEvaluatorCustomizeButtonActionPerformed(evt);
	            }
	        });

	        moveEvaluatorCustomizeButton.setText("Customize");
	        moveEvaluatorCustomizeButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                moveEvaluatorCustomizeButtonActionPerformed(evt);
	            }
	        });

	        moveEvaluatorLabel.setText("Move Evaluator");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(30, 30, 30)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(recurseDepthLabel)
	                            .addComponent(nicknameLabel)
	                            .addComponent(hashSizeLabel))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(nicknameTextField)
	                            .addComponent(recurseDepthTextField)
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                                .addComponent(hashSizeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(hashSizeUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                    .addGroup(layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(16, 16, 16)
	                                .addComponent(moveEvaluatorLabel)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(moveEvaluatorCustomizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                    .addComponent(boardEvaluatorLabel)
	                                    .addComponent(selectionAlgorithmLabel))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(selectionAlgorithmComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(boardEvaluatorCustomizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	                            .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
	                .addContainerGap())
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(nicknameLabel)
	                    .addComponent(nicknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(recurseDepthLabel)
	                    .addComponent(recurseDepthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(hashSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(hashSizeLabel)
	                    .addComponent(hashSizeUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(selectionAlgorithmLabel)
	                    .addComponent(selectionAlgorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(boardEvaluatorLabel)
	                    .addComponent(boardEvaluatorCustomizeButton))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(moveEvaluatorLabel)
	                    .addComponent(moveEvaluatorCustomizeButton))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addContainerGap())
	        );
	    }// </editor-fold>                        

	    private void nicknameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
	        // TODO add your handling code here:
	    }                                                 

	    private void hashSizeUnitComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                     
	        // TODO add your handling code here:
	    }                                                    

	    private void boardEvaluatorCustomizeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                              
	        // TODO add your handling code here:
	    }                                                             

	    private void moveEvaluatorCustomizeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                             
	        // TODO add your handling code here:
	    }                                                            

	    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
	        // TODO add your handling code here:
	    }                                             

	    private void selectionAlgorithmComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                           
	        // TODO add your handling code here:
	    }                                                          

	    private void recurseDepthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                      
	        // TODO add your handling code here:
	    }                                                     

	    private void hashSizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
	        // TODO add your handling code here:
	    }                                                 


	    // Variables declaration - do not modify                     
	    private javax.swing.JButton boardEvaluatorCustomizeButton;
	    private javax.swing.JLabel boardEvaluatorLabel;
	    private javax.swing.JButton confirmButton;
	    private javax.swing.JLabel hashSizeLabel;
	    private javax.swing.JTextField hashSizeTextField;
	    private javax.swing.JComboBox<String> hashSizeUnitComboBox;
	    private javax.swing.JButton moveEvaluatorCustomizeButton;
	    private javax.swing.JLabel moveEvaluatorLabel;
	    private javax.swing.JLabel nicknameLabel;
	    private javax.swing.JTextField nicknameTextField;
	    private javax.swing.JLabel recurseDepthLabel;
	    private javax.swing.JTextField recurseDepthTextField;
	    private javax.swing.JComboBox<String> selectionAlgorithmComboBox;
	    private javax.swing.JLabel selectionAlgorithmLabel;
	    // End of variables declaration                   
	}
}
