package nuchess.ui.root.view;

import javax.swing.JDialog;

import nuchess.engine.Color;
import nuchess.player.Player;
import nuchess.player.human.Human;
import nuchess.ui.root.control.RootControl;

public class GameConstructorDialog extends JDialog
{
	private static final long serialVersionUID = 2580607268440803679L;
	
	private Player whitePlayer, blackPlayer;
	private ContentPanel contentPanel;
	private PlayerConstructorDialog wpcd, bpcd;
	
	public RootControl control;
	
	public GameConstructorDialog()
	{
		contentPanel = new ContentPanel();
		whitePlayer = new Human("Default White");
		blackPlayer = new Human("Default Black");
		wpcd = new PlayerConstructorDialog(Color.WHITE);
		bpcd = new PlayerConstructorDialog(Color.BLACK);
		control = null;
		
		wpcd.setTitle("Choose White Player");
		wpcd.gcd = this;
		
		bpcd.setTitle("Choose Black Player");
		bpcd.gcd = this;
		
		add(contentPanel);
		
		setSize(560, 170);
		setResizable(false);
		setTitle("New Game");
	}
	
	public void hideDialog()
	{
		setVisible(false);
	}
	
	public void setWhitePlayer(Player player)
	{
		whitePlayer = player;
		contentPanel.setWhitePlayerUsername(player.getUsername());
	}
	
	public void setBlackPlayer(Player player)
	{
		blackPlayer = player;
		contentPanel.setBlackPlayerUsername(player.getUsername());
	}
	
	/**
	 *
	 * @author Jacob Cohen
	 */
	private class ContentPanel extends javax.swing.JPanel {
		
		private static final long serialVersionUID = 7934062575202116558L;
		
		/**
	     * Creates new form NewJPanel
	     */
	    public ContentPanel() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {
	        java.awt.GridBagConstraints gridBagConstraints;

	        whiteLabel = new javax.swing.JLabel();
	        whitePlayerUsernameLabel = new javax.swing.JLabel();
	        chooseWhitePlayerButton = new javax.swing.JButton();
	        blackLabel = new javax.swing.JLabel();
	        blackPlayerUsernameLabel = new javax.swing.JLabel();
	        chooseBlackPlayerButton = new javax.swing.JButton();
	        FENLabel = new javax.swing.JLabel();
	        FENTextField = new javax.swing.JTextField();
	        playButton = new javax.swing.JButton();

	        setLayout(new java.awt.GridBagLayout());

	        whiteLabel.setText("WHITE");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
	        add(whiteLabel, gridBagConstraints);

	        whitePlayerUsernameLabel.setText("Default White");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 1;
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.gridwidth = 16;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
	        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
	        add(whitePlayerUsernameLabel, gridBagConstraints);

	        chooseWhitePlayerButton.setText("Choose Player");
	        chooseWhitePlayerButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                chooseWhitePlayerButtonActionPerformed(evt);
	            }
	        });
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 17;
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
	        add(chooseWhitePlayerButton, gridBagConstraints);

	        blackLabel.setText("BLACK");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 1;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
	        add(blackLabel, gridBagConstraints);

	        blackPlayerUsernameLabel.setText("Default Black");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 1;
	        gridBagConstraints.gridy = 1;
	        gridBagConstraints.gridwidth = 16;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
	        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
	        add(blackPlayerUsernameLabel, gridBagConstraints);

	        chooseBlackPlayerButton.setText("Choose Player");
	        chooseBlackPlayerButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                chooseBlackPlayerButtonActionPerformed(evt);
	            }
	        });
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 17;
	        gridBagConstraints.gridy = 1;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
	        add(chooseBlackPlayerButton, gridBagConstraints);

	        FENLabel.setText("FEN");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 2;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
	        add(FENLabel, gridBagConstraints);

	        FENTextField.setText("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1");
	        FENTextField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                FENTextFieldActionPerformed(evt);
	            }
	        });
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 1;
	        gridBagConstraints.gridy = 2;
	        gridBagConstraints.gridwidth = 17;
	        gridBagConstraints.ipadx = 100;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
	        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
	        add(FENTextField, gridBagConstraints);

	        playButton.setText("PLAY");
	        playButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                playButtonActionPerformed(evt);
	            }
	        });
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 3;
	        gridBagConstraints.gridwidth = 18;
	        add(playButton, gridBagConstraints);
	    }// </editor-fold>                        

	    private void FENTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        // TODO add your handling code here:
	    }                                            

	    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {     
	    	hideDialog();
	    	control.openNewGameTab(whitePlayer, blackPlayer, FENTextField.getText());
	    }                                          

	    private void chooseWhitePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
	    	wpcd.setLocationRelativeTo(this);
	    	wpcd.setPlayer(whitePlayer);
	    	wpcd.setVisible(true);
	    }                                                       

	    private void chooseBlackPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {    
	    	bpcd.setLocationRelativeTo(this);
	    	bpcd.setPlayer(blackPlayer);
	    	bpcd.setVisible(true);
	    }                                                       
	    
	    public void setWhitePlayerUsername(String username)
	    {
	    	whitePlayerUsernameLabel.setText(username);
	    }
	    
	    public void setBlackPlayerUsername(String username)
	    {
	    	blackPlayerUsernameLabel.setText(username);
	    }
	    
	    // Variables declaration - do not modify                     
	    private javax.swing.JLabel FENLabel;
	    private javax.swing.JTextField FENTextField;
	    private javax.swing.JLabel blackLabel;
	    private javax.swing.JLabel blackPlayerUsernameLabel;
	    private javax.swing.JButton chooseBlackPlayerButton;
	    private javax.swing.JButton chooseWhitePlayerButton;
	    private javax.swing.JButton playButton;
	    private javax.swing.JLabel whiteLabel;
	    private javax.swing.JLabel whitePlayerUsernameLabel;
	    // End of variables declaration                         
	}
}
