package nuchess.ui.root.view;

import javax.swing.JDialog;

public class PlayerConstructorDialog extends JDialog
{
	private static final long serialVersionUID = -1188324272973018664L;
	
	private ContentPanel contentPanel;
	
	public PlayerConstructorDialog()
	{
		contentPanel = new ContentPanel();
		setSize(371, 271);
		setResizable(false);
		add(contentPanel);
	}
	
	public class ContentPanel extends javax.swing.JPanel {

		private static final long serialVersionUID = 3668866825020800009L;
		
		/**
	     * Creates new form NewJPanel1
	     */
	    public ContentPanel() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        playerTypeComboBox = new javax.swing.JComboBox<>();
	        confirmButton = new javax.swing.JButton();
	        usernameTextField = new javax.swing.JTextField();
	        usernameLabel = new javax.swing.JLabel();
	        recurseDepthLabell = new javax.swing.JLabel();
	        selectionAlgorithmLabel = new javax.swing.JLabel();
	        selectionAlgorithmComboBox = new javax.swing.JComboBox<>();
	        moveOrdererLabel = new javax.swing.JLabel();
	        moveOrdererComboBox = new javax.swing.JComboBox<>();
	        boardEvaluatorLabel = new javax.swing.JLabel();
	        boardEvaluatorComboBox = new javax.swing.JComboBox<>();
	        recurseDepthComboBox = new javax.swing.JComboBox<>();
	        playerTypeLabel = new javax.swing.JLabel();

	        playerTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Human", "Computer" }));

	        confirmButton.setText("Confirm");

	        usernameLabel.setText("Username");

	        recurseDepthLabell.setText("Recurse Depth");

	        selectionAlgorithmLabel.setText("Selection Algorithm");

	        selectionAlgorithmComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alphabeta", "Minimax" }));

	        moveOrdererLabel.setText("Move Orderer");

	        moveOrdererComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

	        boardEvaluatorLabel.setText("Board Evaluator");

	        boardEvaluatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

	        recurseDepthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

	        playerTypeLabel.setText("Player Type");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                    .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(usernameLabel)
	                            .addComponent(recurseDepthLabell)
	                            .addComponent(selectionAlgorithmLabel)
	                            .addComponent(playerTypeLabel)
	                            .addComponent(boardEvaluatorLabel)
	                            .addComponent(moveOrdererLabel))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(playerTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(usernameTextField)
	                            .addComponent(selectionAlgorithmComboBox, 0, 200, Short.MAX_VALUE)
	                            .addComponent(recurseDepthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(boardEvaluatorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(moveOrdererComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(usernameLabel)
	                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(playerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(playerTypeLabel))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(recurseDepthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(recurseDepthLabell))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(selectionAlgorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(selectionAlgorithmLabel))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(boardEvaluatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(boardEvaluatorLabel))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(moveOrdererLabel)
	                    .addComponent(moveOrdererComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(confirmButton)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	    }// </editor-fold>                        


	    // Variables declaration - do not modify                     
	    private javax.swing.JComboBox<String> boardEvaluatorComboBox;
	    private javax.swing.JLabel boardEvaluatorLabel;
	    private javax.swing.JButton confirmButton;
	    private javax.swing.JComboBox<String> moveOrdererComboBox;
	    private javax.swing.JLabel moveOrdererLabel;
	    private javax.swing.JComboBox<String> playerTypeComboBox;
	    private javax.swing.JLabel playerTypeLabel;
	    private javax.swing.JComboBox<String> recurseDepthComboBox;
	    private javax.swing.JLabel recurseDepthLabell;
	    private javax.swing.JComboBox<String> selectionAlgorithmComboBox;
	    private javax.swing.JLabel selectionAlgorithmLabel;
	    private javax.swing.JLabel usernameLabel;
	    private javax.swing.JTextField usernameTextField;
	    // End of variables declaration                   
	}
}
